administration-service-config:
  host: "0.0.0.0"
  port: 8083
  hmac-signing-key: temp_signing_key123
administration-db-config:
  driver: "postgres"
  host: localhost
  port: 5432
  name: administration_db
  username: service
  password: 123LocalDBPass