administration-service-config:
  host: "0.0.0.0"
  port: 8080
administration-db-config:
  driver: "postgres"
  host: ${ADMINISTRATION_DB_HOST}
  port: ${ADMINISTRATION_DB_PORT}
  name: administration_db
  username: service
  password: ${ADMINISTRATION_DB_SERVICE_PASS}
